name: Production Deployment

on:
 push:
  branches:
   - main

jobs:
 build:
  name: Type check, lint, format, and test
  runs-on: ubuntu-latest
  steps:
   - name: Cancel previous runs
     uses: styfle/cancel-workflow-action

   - name: Checkout repo
     uses: actions/checkout@v3

   - name: Setup node
     uses: actions/setup-node@v3
     with:
      node-version: 16

   - name: Install npm dependencies
     run: npm ci

   - name: Lint
     run: npm run lint

   - name: Type check
     run: npm run typecheck

   - name: Format
     run: npm run format

   - name: Install Playwright Browsers
     run: npx playwright install --with-deps

   - name: Run Playwright tests
     run: npx playwright test

   - uses: actions/upload-artifact@v3
     if: always()
     with:
      name: playwright-report
      path: playwright-report/
      retention-days: 30
